### ISSUE TITLE
Blender 3.3+ support?

### ISSUE THREAD

**Issue by richobrien** [Durman/BuildingNodesDocs#18]
Hi,

Will Building Nodes support 3.3.1? I see an error if I apply New Building Style to Cube

https://i.imgur.com/RJVHlro.png

**Comment by richobrien** [comment]
Thanks, also if the Gumroad product can have a version number so we can see when you update it?

**Comment by Durman** [comment]
I think will add extra file for version with the fix. Also I'm going to move to [Boosty](https://boosty.to/soluserg/posts/4c59f216-a966-4fa4-b141-056d86d8bbc6?share=post_link) marketplace .Because, with the world splitting into pieces I doubt that I ever will be able to transfer money from Gumroad.

**Comment by Durman** [comment]
@richobrien I added the fixed version of the add-on on Gumroad. Could you check it?

**Comment by richobrien** [comment]
@Durman I can confirm that v1.0.1 works as expected on Blender 3.3.1. Many thanks!
